# -*- coding: utf-8 -*-
"""Final_Brain _Tumer_Segmentation_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBwmzZRlS8kWD8HMUMH_0Pkt9KcmLb7t
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

import kagglehub

# Download latest version
path = kagglehub.dataset_download("sartajbhuvaji/brain-tumor-classification-mri")

print("Path to dataset files:", path)

!kaggle datasets download -d sartajbhuvaji/brain-tumor-classification-mri

!unzip brain-tumor-classification-mri.zip -d brain_tumor_dataset

# !pip install tensorflow
import tensorflow as tf

# Define the dataset path
dataset_path = '/kaggle/input/brain-tumor-classification-mri'  # Set to your dataset directory

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    dataset_path + '/Training',    # Adjust if needed
    image_size=(224, 224),
    batch_size=32
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    dataset_path + '/Testing',     # Adjust if needed
    image_size=(224, 224),
    batch_size=32
)

import numpy as np
import pandas as pd

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        #print(os.path.join(dirname, filename))
        pass # Keeping loop valid without printing

#Importing Libraries We import essential modules from Keras to build the CNN model, and sklearn for evaluating accuracy.
import keras
from keras.models import Sequential
from keras.layers import Conv2D, Flatten, Dense, MaxPooling2D, Dropout
from sklearn.metrics import accuracy_score

!pip install opencv-python

import ipywidgets as widgets  # For interactive widgets (optional UI elements)
import io  # For handling byte streams (image loading)
from PIL import Image  # To open and process image files
import tqdm  # For displaying progress bars
from sklearn.model_selection import train_test_split  # To split dataset into training and testing sets
import cv2  # OpenCV for image processing (resizing, reading, etc.)
from sklearn.utils import shuffle  # To shuffle dataset randomly
import tensorflow as tf  # Main deep learning framew

import cv2
import numpy as np
import os

X_train = []
Y_train = []
image_size = 150
labels = ['glioma_tumor', 'meningioma_tumor', 'no_tumor', 'pituitary_tumor']

# Load training images
for i in labels:
    folderPath = os.path.join('/kaggle/input/brain-tumor-classification-mri/Training', i)
    for j in os.listdir(folderPath):
        img = cv2.imread(os.path.join(folderPath, j))  # Read image
        img = cv2.resize(img, (image_size, image_size))  # Resize to 150x150 #Fixed indentation here
        X_train.append(img)
        Y_train.append(i)  # Append label

# Load testing images
for i in labels:
    folderPath = os.path.join('/kaggle/input/brain-tumor-classification-mri/Testing', i)
    for j in os.listdir(folderPath):
        img = cv2.imread(os.path.join(folderPath, j))
        img = cv2.resize(img, (image_size, image_size))
        X_train.append(img)
        Y_train.append(i)

# Convert lists to numpy arrays
X_train = np.array(X_train)
Y_train = np.array(Y_train)

from sklearn.utils import shuffle

# Shuffle the image data and labels together to randomize input order
X_train, Y_train = shuffle(X_train, Y_train, random_state=101)

# Print the shape of the image dataset
print(X_train.shape)

# Ensure labels match the number of images (in case of mismatch)
Y_train = Y_train[:X_train.shape[0]]

# Split the dataset into 90% training and 10% testing data
X_train, X_test, y_train, y_test = train_test_split(X_train, Y_train, test_size=0.1, random_state=101)

# Check the shape of the train and test sets
print(X_train.shape, X_test.shape)

# Convert labels to list if they are numpy arrays
y_train = y_train.tolist() if isinstance(y_train, np.ndarray) else y_train
y_test = y_test.tolist() if isinstance(y_test, np.ndarray) else y_test

# Convert string labels into integer indices for training
y_train_new = []
for i in y_train:
    if i in labels:
        y_train_new.append(labels.index(i))  # Find index of the label
    else:
       y_train_new.append(-1)  # Handle unexpected labels
y_train = np.array(y_train_new)
y_train = tf.keras.utils.to_categorical(y_train, num_classes=len(labels))  # Apply one-hot encoding

# Repeat for test labels
y_test_new = []
for i in y_test:
    if i in labels:
        y_test_new.append(labels.index(i))
    else:
        y_test_new.append(-1)
y_test = np.array(y_test_new)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=len(labels))

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dropout, Flatten, Dense

model = Sequential()
model.add(Conv2D(64, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Dropout(0.3))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.3))

model.add(Conv2D(256, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Dropout(0.3))

model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(4, activation='softmax'))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    zoom_range=0.1,
    width_shift_range=0.05,
    height_shift_range=0.05,
    horizontal_flip=True
)

model.summary()

model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

print(X_train.shape)  # (2611, 150, 150, 3)
print(y_train.shape)  # (2611,)

from tensorflow.keras.optimizers import Adam
model.compile(optimizer=Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)
from tensorflow.keras.callbacks import ReduceLROnPlateau

lr_reduce = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=3,
    min_lr=1e-7
)


history = model.fit(
    X_train,
    y_train,
    epochs=50,
    validation_split=0.1,
    callbacks=[early_stop]
)

model.save('braintumor.h5')

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
epochs = range(len(acc))

fig = plt.figure(figsize=(14,7))
plt.plot(epochs, acc, 'r', label="Training Accuracy")
plt.plot(epochs, val_acc, 'b', label="Validation Accuracy")
plt.legend(loc='upper left')
plt.show()

loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(len(loss))

fig = plt.figure(figsize=(14,7))
plt.plot(epochs, loss, 'r', label="Training loss")
plt.plot(epochs, val_loss, 'b', label="Validation loss")
plt.legend(loc='upper left')
plt.show()

img = cv2.imread('/kaggle/input/brain-tumor-classification-mri/Training/pituitary_tumor/p (100).jpg')
img = cv2.resize(img, (150, 150))
img_array = np.array(img)
img_array.shape

img_array = img_array .reshape (1,150,150,3)
img_array.shape

from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# Load the image
img = image.load_img('/kaggle/input/brain-tumor-classification-mri/Training/pituitary_tumor/p (100).jpg')

# Show the image
plt.imshow(img, interpolation='nearest')
plt.axis('off')  # Optional: turn off axis
plt.show()       # ✅ Correct way to show the image

import glob
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

image_paths = glob.glob("/kaggle/input/brain-tumor-classification-mri/Training/pituitary_tumor/*.jpg")

for path in image_paths[:5]:   # show first 5 images
    img = image.load_img(path)
    plt.imshow(img)
    plt.title(path)
    plt.axis('off')
    plt.show()

for path in image_paths[:5]:
    img = image.load_img(path, target_size=(150,150))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    pred = model.predict(img_array)

    plt.imshow(image.load_img(path))
    plt.axis('off')

    classes = ['glioma', 'meningioma', 'pituitary', 'no_tumor']
    print("Prediction:", classes[np.argmax(pred)])
    plt.show()

plt.imshow(img)
plt.axis('off')
plt.show()

a = model.predict(img_array)
indices = a.argmax()
indices

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Assuming X_test and y_test are your validation data
y_pred_classes = np.argmax(model.predict(X_test), axis=1)  # Using X_test instead of X_val

# ... (rest of the code remains the same, replacing X_val with X_test and y_val with y_test) ...

# Make sure y_test is integer labels
# If y_test is one-hot encoded, convert it:
if y_test.ndim == 2:
    y_test_classes = np.argmax(y_test, axis=1)
else:
    y_test_classes = y_test

# Step 2: Create confusion matrix
cm = confusion_matrix(y_test_classes, y_pred_classes)

# ... (rest of the code)

print(classification_report(y_test_classes, y_pred_classes))

from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Predict the classes
y_pred_classes = np.argmax(model.predict(X_test), axis=1)

# If y_test is one-hot encoded
if y_test.ndim == 2:
    y_test_classes = np.argmax(y_test, axis=1)
else:
    y_test_classes = y_test

# Create confusion matrix
cm = confusion_matrix(y_test_classes, y_pred_classes)

# Plot confusion matrix
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap='Blues', cbar=False)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

# Print classification report
print(classification_report(y_test_classes, y_pred_classes))

model.save("brain_tumor_model.h5")   # Saves architecture + weights

import tensorflow as tf
model = tf.keras.models.load_model("brain_tumor_model.h5")

from google.colab import files
files.download("brain_tumor_model.h5")

